# Default values for merbridge.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# some settings of merbridge when start up
name: access
namespace: access-system
revisionHistoryLimit: 10
labels:
  access.io/access-name: access
nodeSelector:
  kubernetes.io/arch: amd64

image:
  hub: fishpro3
  repository: access
  tag: v1.0
  pullPolicy: Always

resources:
  container:
    limit:
      cpu: 300m
      memory: 200Mi
    request:
      cpu: 100m
      memory: 200Mi
