apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- toYaml .Values.labels | nindent 6 }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
    spec:
      hostNetwork: true
      containers:
      - image: "{{ .Values.image.hub }}/{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        name: {{ .Values.name }}
        command:
          - /manager
        resources:
          requests:
            cpu: {{ .Values.resources.container.request.cpu }}
            memory: {{ .Values.resources.container.request.memory }}
          limits:
            cpu: {{ .Values.resources.container.limit.cpu }}
            memory: {{ .Values.resources.container.limit.memory }}
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /host/var/run
            name: host-var-run
            mountPropagation: Bidirectional
      nodeSelector:
        {{- toYaml .Values.nodeSelector | nindent 8 }}
      priorityClassName: system-node-critical
      restartPolicy: Always
      serviceAccount: {{ .Values.name }}
      serviceAccountName: {{ .Values.name }}
      volumes:
        - hostPath:
            path: /var/run
          name: host-var-run